#!/bin/bash

# vim: set ft=sh ts=2 sw=2 sts=2 et sta:
#
# install bash completion for s5cmd
# https://github.com/peak/s5cmd

safewhich s5cmd || exit

COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
complete -C "$(command -v s5cmd)" s5cmd