#!/bin/bash
#
# Completion script for:
#
# github.com/psibi/tldr-hs

safewhich tldr || return 0

_tldr_complete() {
    local cur opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

    opts=$(tldr --list | tr ',' '\n')
    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
}

complete -F _tldr_complete tldr
