# vim: set ft=sh ts=2 sw=2 sts=2 et sta:
#
# FZF setup (command line Fuzzy Finder)
#
# https://github.com/junegunn/fzf

# if fzf is installed, load key bindings and bash completion scripts
# see https://github.com/junegunn/fzf
if [ -f "$HOME/.fzf/bin/fzf" ]; then
    # fzf.bash is autogenerated during fzf installation
    [ -f ~/.fzf.bash ] && source ~/.fzf.bash
fi
