#!/bin/sh
# from http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT

git ls-files | egrep '\.go$' | \
  gotags --tag-relative -L - -f "$dir/$$.tags"
echo done with $?
mv "$dir/$$.tags" "$dir/tags"
